### ISSUE TITLE
Scatter connect error - local.get-scatter.com

### ISSUE THREAD

**Issue by dgthbss** [GetScatter/scatter-js#138]
I use @scatterjs/core - 2.7.44, @scatterjs/eosjs2 - 1.5.26, Scatter Desktop v11.0.1.
My Scatter Desktop v11.0.1 Local socket ports is 50005, 50006.
 
![1](https://user-images.githubusercontent.com/52309908/65407759-81d33b00-de1e-11e9-8718-bf14b94575a8.png)

![2](https://user-images.githubusercontent.com/52309908/65407771-8a2b7600-de1e-11e9-8103-e0933b8d71cb.png)

One can connect but others are not.

**Comment by matei-radu** [comment]
That is normal.

ScatterJS will attempt to connect to multiple ports because it is unsure which one your Scatter Desktop is using:
- `50005` (`50006` for HTTPS)
- `51505` (`51506` for HTTPS)
- `53005` (`53006` for HTTPS)
- `54505` (`54506` for HTTPS)
- `56005` (`56006` for HTTPS)

Your Scatter Desktop is using `50006` so only the connection to `https://loca.get-scatter.com:50006` succeeded.

In general, as long as one of the attempts succeeds the other ones that fail can be safely ignored.

**Comment by nsjames** [comment]
That's 100% correct. Sadly we can't catch and hide those errors as they are thrown by the browser. Makes things messy, but the fallback ports make connections much more resilient for machines who have ports locked (like those using docker)
