### ISSUE TITLE
2.7.47 is incompatible with ual-scatter

### ISSUE THREAD

**Issue by conr2d** [GetScatter/scatter-js#147]
ual-scatter provided by EOSIO is using old version of scatter-js packages (scatterjs-core and scatterjs-plugin-eosjs2), so I'm writing a patch for replacing them with the latest one. (EOSIO/ual-scatter#54)
However, its searching for scatter is stuck with @scatterjs/core@2.7.47. With 2.7.46 or earlier, this issue doesn't occur. When using scatter-js directly (not with ual), there's no issue either. Is there any clue what change of 2.7.47 can cause this kind of issue?

**Comment by nsjames** [comment]
Not sure what you mean by " its searching for scatter is stuck". 
Can you give me an example?

**Comment by conr2d** [comment]
https://imgur.com/a/NyIvfVX

This is a screenshot of modal popup provided by universal authenticator. In normal scenario, it activates "Scatter" button after connecting to scatter, but it keep showing process dots (...) or show error message that it failed to find any authenticators.

**Comment by nsjames** [comment]
And Scatter connects properly to other apps?
What about any console errors?

**Comment by bradlhart** [comment]
I've been working on ual-scatter following conr2d's work and I ran into two logs/errors.

First one, since I was using an app with spaces in the name, I got 'No socket found' on Scatter Desktop.  Related: https://github.com/GetScatter/ScatterDesktop/pull/480

Second one, since UAL was connecting several times, I got 'Websocket is already in CLOSING or CLOSED state' in my browser console.  Related: https://github.com/GetScatter/scatter-js/issues/156
