### ISSUE TITLE
getIdentity returns null.

### ISSUE THREAD

**Issue by raphaelgodro** [GetScatter/scatter-js#17]
Hello!
### Scatter-js  2.5.1

Yesterday my Scatter Desktop and scatter-js worked fine but today I receive null identities.
I run Scatter Desktop. So basically, my websocket connects fine but ScatterDesktop doesn't pop any window in which I can choose my identity. It sends over a null identity and the getIdentity promise get resolved.

I don't know if the issue is at the Scatter Desktop level or scatter-js, on which side of the websockets there is an issue

**Comment by nsjames** [comment]
Hmm, if this is still happening try seeing if there's any errors in the console of the website or Scatter.

**Comment by seihyunJeong** [comment]
Hi, getIdentity function returns null  intermittently. The probability of the null is approximately 1.5% in my experiment(about 15 out of 1000).  The only solution for this is to remove the Scatter ID and recreate it repeating this cycle. This is critical since authenticate function returns null signature too. Scatter chrome extension seems to be more concrete than Scatter Desktop and Scatter mobile.

**Comment by nsjames** [comment]
Need some errors guys. I've yet to be able to reproduce this. 

Need errors from the website ( probably won't get thrown ) or errors from inside Scatter Desktop ( </> button inside settings will open console )
