### ISSUE TITLE
eosjs and eosjs2 should be listed as peer dependencies

### ISSUE THREAD

**Issue by crazycoder1988** [GetScatter/scatter-js#43]
Otherwise user may not use eosjs/2 independently.

**Comment by nsjames** [comment]
You mean them having to pull in their own versions of eosjs/2?

**Comment by crazycoder1988** [comment]
Yes, exactly! There are multiple benefits. The main benefit is that, If user want to support using eosjs2 without scatter (while also reserve the usage), then user won't import another eosjs2 instance, which means smaller bundle file size. If you have some requirements for the version of user's eosjs2, then it should be listed in the peer dependency version. See https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by nsjames** [comment]
ScatterJS doesn't come with `eosjs` or `eosjs2`. It's up to the developer to provide the version of those libraries they are using so that they aren't locked into certain versions *because that's what we're using*.

**Comment by crazycoder1988** [comment]
But it does come with a version in plugins 😅 https://github.com/GetScatter/scatter-js/blob/master/packages/plugin-eosjs2/package.json#L7

**Comment by nsjames** [comment]
Errr, not really. It's listed in the dependencies but never pulled into the packed or built libraries so it doesn't exist inside of the files you'd be importing. I removed it from my local ( and on the `eosjs` on too which seemed to be there as well ) and have pushed it to the repo, but it can't be pushed to npm or the cdn because no changes happened on the exports so no versioning can occur. 

9b56a8fa9d412434ea1f05f50b28a9a626511d1d

**Comment by crazycoder1988** [comment]
Oh, got it. Thanks a lot!
