### ISSUE TITLE
Be friendly to the eos game?

### ISSUE THREAD

**Issue by jacktang** [GetScatter/scatter-js#50]
Hello,

I try to create some kind game like space invaders, before starting, I play the demo on https://eosauthority.com/space/. And I find if the client sends request (move LEFT/RIGHT) to contract, the scatter pops up. Anyway to make scatter be friendly to the game? say auto-confirm the request?

**Comment by jacktang** [comment]
And more, in the RPG game, if the player loses one life, I think he is not going to confirm the transaction.

**Comment by nsjames** [comment]
Scatter itself implements a whitelisting/permissions system. It's up to the user to whitelist given actions so that they don't have to keep accepting them.

> And more, in the RPG game, if the player loses one life, I think he is not going to confirm the transaction.

This shouldn't be a transaction sent by the user, it should be an intermediate authoritative server which handles that in the name of the **game**, not the user.
