### ISSUE TITLE
how to build eos dapp browser?

### ISSUE THREAD

**Issue by sfsw** [GetScatter/scatter-js#67]
I wanna run eos game like betdice, eosjack... in native webview(iOS & Android), do I need to copy all scatter-core/src all files to assets and make JSBridge ?  any better idea?

i found websocket way, but can any one upload some demo?

**Comment by sangramsam** [comment]
Have you find any solution for dapp browser

**Comment by nsjames** [comment]
We don't really have any boilerplates for this. In general you'd need to mimic the `scatterjs` API inside your wallet.

https://github.com/GetScatter/scatter-js/blob/master/packages/core/src/index.js#L110

Take note that there are some deprecated methods which also need to be supported for backwards compatibility since you're mimicking the interface. 
https://github.com/GetScatter/scatter-js/blob/master/packages/core/src/index.js#L257

**Comment by dinghu** [comment]
> I wanna run eos game like betdice, eosjack... in native webview(iOS & Android), do I need to copy all scatter-core/src all files to assets and make JSBridge ? any better idea?
> 
> i found websocket way, but can any one upload some demo?

hi,have you find a solution for this issue ?
